services:
  postgres:
    image: postgres:16
    container_name: lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: lab-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7
    container_name: lab-redis
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.10.5
    container_name: lab-airflow-init
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/airflow_meta
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres/airflow_meta
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: lab-airflow-webserver
    restart: unless-stopped
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/airflow_meta
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres/airflow_meta
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: lab-airflow-scheduler
    restart: unless-stopped
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/airflow_meta
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres/airflow_meta
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: airflow scheduler

  airflow-worker:
    image: apache/airflow:2.10.5
    container_name: lab-airflow-worker
    restart: unless-stopped
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/airflow_meta
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres/airflow_meta
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: airflow celery worker

  jenkins:
    image: jenkins/jenkins:lts
    container_name: lab-jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jupyter:
    image: quay.io/jupyter/scipy-notebook
    container_name: lab-jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: admin

  alert-simulator:
    build: ./simulator
    container_name: thetabar-alert-simulator
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: app_db
      DB_USER: admin
      DB_PASSWORD: admin
      SLEEP_SECONDS: 30

  ic-backend:
    build: ./backend
    container_name: lab-ic-backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: app_db
      DB_USER: admin
      DB_PASSWORD: admin
      JWT_SECRET: local-dev-ic-secret-change-later
      JWT_EXPIRE_MINUTES: 720

  ic-frontend:
    build: ./ic-frontend
    container_name: lab-ic-frontend
    restart: unless-stopped
    depends_on:
      - ic-backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  jenkins_home:
  pgadmin_data:
